run:
  timeout: 5m
  tests: false
issues:
  exclude-rules:
    - path: 'internal/akcp/sensorProbePlus/sensorProbePlus.go'
      linters:
        - revive
        - stylecheck
linters:
   enable-all: true
   disable:
     - cyclop
     - depguard
     - exhaustivestruct
     - exhaustruct
     - forbidigo
     - forcetypeassert
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - godot
     - goerr113
     - gofumpt
     - gomnd
     - mnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
     - funlen
linters-settings:
  estif:
    min-complexity: 4
  maligned:
    suggest-new: true
