# See documentation at https://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - >-
        -s -w -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.CommitDate}}
release:
  draft: true
  github:
    owner: NETWAYS
    name: check_akcp_sensorprobeXplus
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
